name: pkce
description: Generates code verifier and code challenge pairs for PKCE (Proof Key for Code Exchange).
version: 1.0.0
homepage: https://github.com/nrubin29/dart-pkce

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.4
