name: pkce
description: Generates code verifier and code challenge pairs for PKCE (Proof Key for Code Exchange).
version: 1.1.0+1
homepage: https://github.com/nrubin29/pkce_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
